testTask4/routes/web.php
<?php

    use Illuminate\Support\Facades\Route;

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Route::get(
        '/',
        function () {
            return view('welcome');
        }
    );

//    Route::get(
//        '/Books',
//        function () {
//            return view('Books.index');
//        }
//    );

    Route::get('/search_books', 'BooksController@searchBooks');
    Route::get('/search_authors', 'BooksController@searchAuthors');
    Route::get('/sort_books_by_name', 'BooksController@sortByName');
    Route::get('/sort_authors_by_surname', 'AuthorsController@sortBySurname');
    Route::get('/search_author_name', 'AuthorsController@searchAuthorName');
    Route::get('/search_author_surname', 'AuthorsController@searchAuthorSurname');


    Route::resource('Books', 'BooksController');
    Route::resource('Authors', 'AuthorsController');

testTask4/app/Models/Books.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Books extends Model
{

    protected $table = 'Books';
    protected $primaryKey = 'book_id';
    public $timestamps = false;
    protected $fillable = ['name', 'short_description', 'img',  'publication_date'];


    public function authors()
    {
        return $this->belongsToMany(Authors ::class, 'author_book', 'book_id', 'author_id');
    }

}

testTask4/app/Http/Controllers/BooksController.php
<?php

    namespace App\Http\Controllers;


    use App\Models\Authors;
    use App\Models\Books;
    use Illuminate\Http\Request;
    use Illuminate\Http\Response;

    class BooksController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return Response
         */
        public function index()
        {
            $books = Books::paginate(15);
            return view('Books.index', compact('books'));
        }

        /*compact('books')*/
        /**
         * Show the form for creating a new resource.
         *
         * @return Response
         */
        public function create()
        {
            $authors = Authors::all();
            return view('Books.create', compact('authors'));
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param \Illuminate\Http\Request $request
         * @return Response
         */
        public function store(Request $request)
        {
            $request->validate(
                [
                    'name' => 'required',
                    'short_description',
                    'img' => 'mimes:jpeg,png| max:2048',
                    'publication_date' => 'numeric'
                ]
            );


            $book = new Books(
                [
                    'name' => $request->get('name'),
                    'short_description' => $request->get('short_description'),
                    'img' => $request->file('img')->store('images', 'public'),
                    'publication_date' => $request->get('publication_date')

                ]
            );

            $authors = $request->get('authors');

            $book->save();
            foreach ($authors as $author) {
                $book->authors()->attach($author);
            }


            return redirect('/Books')->with('success', 'Book successfully added!');
        }

        /**
         * Display the specified resource.
         *
         * @param \App\books $post
         * @return Response
         */
        public function show($book)
        {
            $book = Books::find($book);

            return view('Books.show', compact('book'))->render();
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param \App\books $post
         * @return Response
         */
        public function edit($book_id)
        {
            $authors = Authors::all();
            $book = Books::find($book_id);

            return view('Books.edit', ['authors' => $authors, 'book' => $book])->render();
        }

        /**
         * Update the specified resource in storage.
         *
         * @param \Illuminate\Http\Request $request
         * @param $book_id
         * @return Response
         */
        public function update(Request $request, $book_id)
        {
            $request->validate(
                [
                    'name' => 'required',
                    'short_description',
                    'img' => 'mimes:jpg,png| max:2048',
                    'publication_date' => 'numeric'
                ]
            );
            $book = Books::find($book_id);
            $book->name = $request->get('name');
            $book->short_description = $request->get('short_description');
            $book->publication_date = $request->get('publication_date');

            if ($request->get('img')) {
                $book->img = $request->file('img')->store('images', 'public');
            }

            $book->authors()->detach();

            $book->save();


            $book->authors()->attach($request->get('authors'));


            return redirect('/Books')->with('success', 'Book successfully edited!');
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param $book_id
         * @return Response
         */
        public function destroy($book_id)
        {
            $book_id = Books::find($book_id);
            $book_id->delete();

            return redirect('/Books')->with('success', 'Book deleted!');
        }


        public function searchBooks(Request $request)
        {
            $search = $request->get('search');
            $books = Books::with('authors')->where('name', 'LIKE', '%' . $search . '%')->paginate(5);
            return view('Books.index', ['books' => $books]);
        }


        public function searchAuthors(Request $request)
        {
            $search = $request->get('search');
            $books = Books::whereHas(
                'authors',
                function ($q) use ($search) {
                    $q->where('name', 'LIKE', '%' . $search . '%')
                        ->orWhere('surname', 'LIKE', '%' . $search . '%')
                        ->orWhere('patronymic', 'LIKE', '%' . $search . '%');
                }
            )->paginate(5);


            return view('Books.index', ['books' => $books]);
        }


        public function sortByName(Request $request)
        {
            $books = Books::with('Authors')
                ->orderBy('name', 'asc')
                ->paginate(15);
            return view('Books.index', compact('books'));
        }

    }

testTask4/resources/views/Books/create.blade.php
@extends('layouts.app')

@section('title', 'Add book')

@section('content')
    <nav class="navbar navbar-expand-lg navbar-dark bg-success mb-3 navbar-toggleable   ">
        <a class="navbar-brand" href="#">Book Reference</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item custom-control-inline">
                    <a class="nav-link" href="{{ route('Books.index') }}">Books</a>
                    <a class="nav-link" href="{{ route('Authors.index') }}">Authors</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="row">
        <div class="col-lg-6 mx-auto">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li> {{$error}}</li>
                        @endforeach
                    </ul>
                </div><br>
            @endif
            <form enctype="multipart/form-data" method="POST" action="{{ route('Books.store') }}">
                @csrf
                <div class="form-group">
                    <label for="book-name">Book's name</label>
                    <input required type="text" name="name" class="form-control" placeholder="Name" id="book-name"
                           value=" {{ old('name') }}">
                </div>
                <div class="form-group">
                    <label for="book-shortDescription">Short description</label>
                    <textarea class="form-control" name="short_description" rows="3" placeholder="Short description"
                              id="book-shortDescription">{{ old('short-description') }}</textarea>
                </div>
                <div>
                    <p>Upload img</p>
                    <p>
                        <input type="file" name="img" multiple accept="image/jpeg,image/png" id="book-img">
                    </p>
                </div>

                <label for="author">Select Authors:</label>
                <br>
                @foreach ($authors as $author)
                    <input type="checkbox" name="authors[]" id="author-id" value="{{ $author->author_id }}">
                    <label
                        for="author-id"> {{ $author->surname . ' ' .  $author->name . ' ' . $author->patronymic  }}</label>
                    <br>
                @endforeach


                <div class="form-group">
                    <label for="book-pubdate">Publication date</label>
                    <input required type="text" name="publication_date" class="form-control"
                           placeholder="Publication date" id="publication_date"
                           value=" {{ old('publication_date') }}">
                </div>
                <button type="submit" class="btn btn-success">Add book</button>
            </form>

        </div>
    </div
@endsection

testTask4/resources/views/Books/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit book')

@section('content')
    <div class="row">
        <div class="col-lg-6 mx-auto">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li> {{$error}}</li>
                        @endforeach
                    </ul>
                </div><br>
            @endif
            <form enctype="multipart/form-data" method="POST" action="{{ route('Books.update', $book) }}">
                @csrf
                @method('PATCH ')
                <div class="form-group">
                    <label for="book-name">Book's name</label>
                    <input required type="text" name="name" class="form-control" placeholder="Name" id="book-name"
                           value=" {{ $book->name  }}">
                </div>
                <div class="form-group">
                    <label for="book-shortDescription">Short description</label>
                    <textarea class="form-control" name="short_description" rows="3" placeholder="Short description"
                              id="book-shortDescription">{{ $book->short_description }}</textarea>
                </div>
                <div>
                    <p>Img:<img width="200" height="200" src=" {{ asset('/storage/' . $book->img)}} " alt="Book-img">
                    </p>
                    <p>Upload img</p>
                    <input type="file" name="img" multiple accept="image/jpeg,image/png" id="book-img">

                </div>
                <div class="form-group">
                    <label for="author">Select Authors:</label>
                    <br>
                    @foreach ($authors as $author)
                        <input type="checkbox" name="authors[]" id="author-id" value="{{ $author->author_id }}">
                        <label
                            for="author-id"> {{ $author->surname . ' ' .  $author->name . ' ' . $author->patronymic  }}</label>
                        <br>
                    @endforeach

                </div>
                <div class="form-group">
                    <label for="book-pubdate">Publication date</label>
                    <input required type="text" name="publication_date" class="form-control"
                           placeholder="Publication date" id="publication_date"
                           value=" {{ $book->publication_date }}">
                </div>
                <button type="submit" class="btn btn-success">Edit book</button>
            </form>
        </div>
    </div

@endsection

testTask4/resources/views/Books/index.blade.php
@extends('layouts.app')

@section('title', 'Books')

@section('content')
    <nav class="navbar navbar-expand-lg navbar-dark bg-success mb-3 navbar-toggleable   ">
        <a class="navbar-brand" href="#">Book Reference</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item custom-control-inline">
                    <a class="nav-link" href="{{ route('Books.index') }}">Books</a>
                    <a class="nav-link" href="{{ route('Authors.index') }}">Authors</a>
                </li>
            </ul>
        </div>
    </nav>


    <a href="{{ route('Books.create') }}" class="btn-outline-success display-4">Add book</a>

    @if(session()->get('success'))
        <div class="alert-success">
            {{ session()->get('success') }}
        </div>
    @endif

    <form action="/search_books" method="GET" class="form-inline my-2 my-lg-0 p-2">
        <label>
            <input class="form-control mr-sm-2" name="search" type="search" placeholder="Books search">
        </label>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Books search</button>
    </form>

    <form action="/search_authors" method="GET" class="form-inline my-2 my-lg-0 p-2">
        <label>
            <input class="form-control mr-sm-2" name="search" type="search" placeholder="Authors search">
        </label>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Authors search</button>
    </form>
    <form action="/sort_books_by_name" method="GET" class="form-inline my-2 my-lg-0 p-2">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Sort Books by Name</button>
    </form>

    <table class="table table-striped mt-3">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">ShortDescription</th>
            <th scope="col">Img</th>
            <th scope="col">Authors</th>
            <th scope="col">PubDate</th>
        </tr>
        </thead>
        <tbody>
        @foreach($books as $book)
            <tr>
                <th scope="row">{{ $book->book_id }}</th>
                <td>{{ $book->name }}</td>
                <td>{{ $book->short_description }}</td>
                <td><img width="100" height="100" src=" {{ asset('/storage/' . $book->img)}} " alt="Book-img"></td>
                <td>
                    @foreach($book->authors as $author)
                        {{ $author->surname . ' ' . $author->name . ' ' . $author->patronymic . '; '}}
                    @endforeach
                </td>
                <td>{{ $book->publication_date }}</td>
                <td class="table-buttons">

                    <button type="button" class="btn btn-success"
                            onClick=editBook("{{ route('Books.show', $book->book_id) }}")>
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </button>

                    <button type="button" class="btn btn-primary"
                            onClick=editBook("{{ route('Books.edit', $book->book_id) }}")>
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </button>

                    <form method="POST" action="{{ route('Books.destroy', $book->book_id) }}">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach

        <div style="display: none" class="modal" id="editBookModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Edit book</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div id="modal-body" class="modal-body">

                    </div>
                </div>
            </div>
        </div>

        <script>
            function editBook(url) {
                $.ajax({
                    method: 'GET',
                    url: url,
                    data: {
                        dataType: 'json',
                        contentType: 'application/json',
                    }
                })
                    .done(function (data) {
                        $('div.modal-body').html(data);
                        $('#editBookModal').modal('show');
                    })
                    .fail(function () {
                        alert("error");
                    });
            }
        </script>
        </tbody>
    </table>
    {{ $books->links() }}

@endsection

testTask4/resources/views/Books/show.blade.php
@extends('layouts.app')

@section('title', 'Show book')

@section('content')

    <div class="card">
        <div class="card-body">

            <h3>Name: {{ $book->name }}</h3>
            <p>Short description:{{ $book->short_description }}</p>
            <p>Img:
                <img width="200" height="200" src=" {{ asset('/storage/' . $book->img)}} " alt="Book-img">
            </p>
            <p>Author: @foreach($book->authors as $author)
                    {{ $author->surname . ' ' . $author->name . ' ' . $author->patronymic . '; '}}
                @endforeach</p>
            <p><b>Publication date: {{ $book->publication_date }}</b></p>
        </div>
    </div>

@endsection