testTask4/routes/web.php
<?php

    use Illuminate\Support\Facades\Route;

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Route::get(
        '/',
        function () {
            return view('welcome');
        }
    );

//    Route::get(
//        '/Books',
//        function () {
//            return view('Books.index');
//        }
//    );

    Route::get('/search_books', 'BooksController@searchBooks');
    Route::get('/search_authors', 'BooksController@searchAuthors');
    Route::get('/sort_books_by_name', 'BooksController@sortByName');
    Route::get('/sort_authors_by_surname', 'AuthorsController@sortBySurname');
    Route::get('/search_author_name', 'AuthorsController@searchAuthorName');
    Route::get('/search_author_surname', 'AuthorsController@searchAuthorSurname');


    Route::resource('Books', 'BooksController');
    Route::resource('Authors', 'AuthorsController');

testTask4/app/Models/Authors.php
<?php

    namespace App\Models;

    use Illuminate\Database\Eloquent\Model;

    class Authors extends Model
    {
        protected $table = 'Authors';
        protected $primaryKey = 'author_id';
        public $timestamps = false;
        protected $fillable = ['name', 'surname', 'patronymic'];


        public function books()
        {
            return $this->belongsToMany(Authors ::class, 'author_book', 'author_id', 'book_id');
        }
    }

testTask4/app/Http/Controllers/AuthorsController.php
<?php

    namespace App\Http\Controllers;

    use App\Models\authors;
    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\DB;

    class AuthorsController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            $authors = authors::paginate(15);

            return view('Authors.index', compact('authors'));
        }

        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            return view('Authors.create');
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param \Illuminate\Http\Request $request
         * @return \Illuminate\Http\Response
         */
        public function store(Request $request)
        {
            $request->validate(
                [
                    'name' => 'required | alpha',
                    'surname' => 'required | min:3 | alpha',
                    'patronymic' => 'alpha'
                ]
            );

            $author = new authors(
                [
                    'name' => $request->get('name'),
                    'surname' => $request->get('surname'),
                    'patronymic' => $request->get('patronymic')
                ]
            );

            $author->save();

            return redirect('/Authors')->with('success', 'Author successfully added');
        }

        /**
         * Display the specified resource.
         *
         * @param \App\Models\authors $authors
         * @return \Illuminate\Http\Response
         */
        public function show($author)
        {
            $author = Authors::find($author);
            return view('Authors.show', compact('author'));
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param \App\Models\authors $authors
         * @return \Illuminate\Http\Response
         */
        public function edit($author_id)
        {
            $author = Authors::find($author_id);

            return view('Authors.edit', compact('author'))->render();
        }

        /**
         * Update the specified resource in storage.
         *
         * @param \Illuminate\Http\Request $request
         * @param \App\Models\authors $authors
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, $author_id)
        {
            $request->validate(
                [
                    'name' => 'required|alpha',
                    'surname' => 'required | min:3 | alpha',
                    'patronymic' => 'alpha'
                ]
            );

            $author = Authors::find($author_id);
            $author->name = $request->get('name');
            $author->surname = $request->get('surname');
            $author->patronymic = $request->get('patronymic');

            $author->save();

            return redirect('/Authors')->with('success', 'Author successfully edited!')->render();
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param \App\Models\authors $authors
         * @return \Illuminate\Http\Response
         */
        public function destroy($author_id)
        {
            $author_id = Authors::find($author_id);
            $author_id->delete();

            return redirect('/Authors')->with('success', 'Author deleted!');
        }

        public function searchAuthorName(Request $request)
        {
            $search = $request->get('search');
            $authors = DB::table('authors')->where('name', 'LIKE', '%' . $search . '%')->paginate(5);
            return view('Authors.index', ['authors' => $authors]);
        }

        public function searchAuthorSurname(Request $request)
        {
            $search = $request->get('search');
            $authors = DB::table('authors')->where('surname', 'LIKE', '%' . $search . '%')->paginate(5);
            return view('Authors.index', ['authors' => $authors]);
        }

        public function sortBySurname(Request $request)
        {
            $authors = DB::table('Authors')
                ->orderBy('surname', 'asc')->paginate(5);
            return view('Authors.index', compact('authors'));
        }


    }

testTask4/resources/views/Authors/create.blade.php
@extends('layouts.app')

@section('title', 'Add author')

@section('content')
    <nav class="navbar navbar-expand-lg navbar-dark bg-success mb-3 navbar-toggleable   ">
        <a class="navbar-brand" href="#">Book Reference</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item custom-control-inline">
                    <a class="nav-link" href="{{ route('Books.index') }}">Books</a>
                    <a class="nav-link" href="{{ route('Authors.index') }}">Authors</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="row">
        <div class="col-lg-6 mx-auto">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li> {{$error}}</li>
                        @endforeach
                    </ul>
                </div><br>
            @endif
            <form enctype="multipart/form-data" method="POST" action="{{ route('Authors.store') }}">
                @csrf
                <div class="form-group">
                    <label for="book-name">Author name</label>
                    <input required type="text" name="name" class="form-control" placeholder="Author name"
                           id="author-name"
                           value=" {{ old('name') }}">
                </div>
                <div class="form-group">
                    <label for="author-surname">Author surname</label>
                    <input required type="text" name="surname" class="form-control" placeholder="Author surname"
                           id="author-surnme"
                           value=" {{ old('surname') }}">
                </div>
                <div class="form-group">
                    <label for="book-patronymic">Author patronymic</label>
                    <input required type="text" name="patronymic" class="form-control"
                           placeholder="Author patronymic" id="author-patronymic"
                           value=" {{ old('patronymic') }}">
                </div>
                <button type="submit" class="btn btn-success">Add author</button>
            </form>
        </div>
    </div
@endsection

testTask4/resources/views/Authors/edit.blade.php
@extends('layouts.app')

@section('title', 'Add author')

@section('content')
    <div class="row">
        <div class="col-lg-6 mx-auto">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li> {{$error}}</li>
                        @endforeach
                    </ul>
                </div><br>
            @endif
            <form enctype="multipart/form-data" method="POST" action="{{ route('Authors.update', $author )}}">
                @csrf
                @method('PATCH ')
                <div class="form-group">
                    <label for="book-name">Author name</label>
                    <input required type="text" name="name" class="form-control" placeholder="Author name"
                           id="author-name"
                           value=" {{ $author->name }}">
                </div>
                <div class="form-group">
                    <label for="author-surname">Author surname</label>
                    <input required type="text" name="surname" class="form-control" placeholder="Author surname"
                           id="author-surnme"
                           value=" {{ $author->surname }}">
                </div>
                <div class="form-group">
                    <label for="book-patronymic">Author patronymic</label>
                    <input required type="text" name="patronymic" class="form-control"
                           placeholder="Author patronymic" id="author-patronymic"
                           value=" {{ $author->patronymic }}">
                </div>
                <button type="submit" class="btn btn-success">Edit author</button>
            </form>
        </div>
    </div
@endsection

testTask4/resources/views/Authors/index.blade.php
@extends('layouts.app')

@section('title', 'Authors')

@section('content')
    <nav class="navbar navbar-expand-lg navbar-dark bg-success mb-3 navbar-toggleable">
        <a class="navbar-brand" href="#">Book Reference</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item custom-control-inline">
                    <a class="nav-link" href="{{ route('Books.index') }}">Books</a>
                    <a class="nav-link" href="{{ route('Authors.index') }}">Authors</a>
                </li>
            </ul>
        </div>
    </nav>

    <a href="{{ route('Authors.create') }}" class="btn-outline-success display-4">Add author</a>

    @if(session()->get('success'))
        <div class="alert-success">
            {{ session()->get('success') }}
        </div>
    @endif
    <form action="/search_author_name" method="GET" class="form-inline my-2 my-lg-0 p-2">
        <label>
            <input class="form-control mr-sm-2" name="search" type="search" placeholder="Name search">
        </label>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Author's name search</button>
    </form>

    <form action="/search_author_surname" method="GET" class="form-inline my-2 my-lg-0 p-2">
        <label>
            <input class="form-control mr-sm-2" name="search" type="search" placeholder="Surname search">
        </label>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Author's surname search</button>
    </form>

    <form action="/sort_authors_by_surname" method="GET" class="form-inline my-2 my-lg-0 p-2">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Sort Authors by Surname</button>
    </form>

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Surname</th>
            <th scope="col">Name</th>
            <th scope="col">Patronymic</th>
        </tr>
        </thead>
        <tbody>
        @foreach($authors as $author)
            <tr>
                <th scope="row">{{ $author->author_id }}</th>
                <td>{{ $author->surname }}</td>
                <td>{{ $author->name }}</td>
                <td>{{ $author->patronymic }}</td>

                <td class="table-buttons">
                    <button type="button" class="btn btn-success"
                            onClick=editBook("{{ route('Authors.show', $author->author_id) }}")>
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </button>

                    <button type="button" class="btn btn-primary"
                            onClick=editBook("{{ route('Authors.edit', $author->author_id) }}")>
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </button>


                    <form method="POST" action="{{ route('Authors.destroy', $author->author_id) }}">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                </td>
                @endforeach

                <div style="display: none" class="modal" id="editBookModal" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Edit book</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div id="modal-body" class="modal-body">
                            </div>
                        </div>
                    </div>
                </div>

                <script>
                    function editBook(url) {
                        $.ajax({
                            method: 'GET',
                            url: url,
                            data: {
                                dataType: 'json',
                                contentType: 'application/json',
                            }
                        })
                            .done(function (data) {
                                $('div.modal-body').html(data);
                                $('#editBookModal').modal('show');
                            })
                            .fail(function () {
                                alert("error");
                            });
                    }
                </script>
            </tr>
        </tbody>
    </table>
    {{ $authors->links() }}
@endsection

testTask4/resources/views/Authors/show.blade.php
@extends('layouts.app')

@section('title', 'Show author')

@section('content')

    <div class="card">
        <div class="card-body">
            <h3>Name: {{ $author->name }}</h3>
            <b><p>Surname: {{ $author->surname  }}</p></b>
            <p>Patronymic: {{ $author->patronymic}}</p>
        </div>
    </div>

@endsection